name: ventas_electronica
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  get: 4.5.1
  http: ^0.13.3
  # share_plus: 3.0.0
  # path_provider: ^2.0.4
  # cached_network_image: ^3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/arduinos/
    - assets/images/modulos/
    - assets/images/node/
    - assets/images/componentes/
    - assets/images/drivers/
    - assets/images/drivers_mp/
    - assets/images/reles/
    - assets/images/mp/
    - assets/images/stm/
    - assets/images/otros/